# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bfctl < Formula
  desc "CLI for backing up and inspecting Betaflight flight controller configuration over USB"
  homepage "https://github.com/justincampbell/bfctl"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/justincampbell/bfctl/releases/download/v0.1.0/bfctl_0.1.0_darwin_amd64.tar.gz"
    sha256 "ccc3e7e24209895142995336dd91f6eb16760743ea8cfc912f350d38a2432335"

    define_method(:install) do
      bin.install "bfctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/justincampbell/bfctl/releases/download/v0.1.0/bfctl_0.1.0_darwin_arm64.tar.gz"
    sha256 "1cbff89f74cf1cdc732b8aa5306794a853e3da535a725185c03e2ac7a76a9c24"

    define_method(:install) do
      bin.install "bfctl"
    end
  end
end
