# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EmojiWeather < Formula
  desc "Emoji weather for your terminal and tmux status bar"
  homepage "https://github.com/justincampbell/emoji-weather"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justincampbell/emoji-weather/releases/download/v0.3.0/emoji-weather_0.3.0_darwin_amd64.tar.gz"
      sha256 "6abefbd41f0bd3f64f8ea5c4851ead74209756d6760279a3c98a5a45c9c8cd33"

      define_method(:install) do
        bin.install "emoji-weather"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justincampbell/emoji-weather/releases/download/v0.3.0/emoji-weather_0.3.0_darwin_arm64.tar.gz"
      sha256 "aef17a334a2be0c4719d0ec0ab4fa5f1960cba7a27cb61346fa98bfad26058cc"

      define_method(:install) do
        bin.install "emoji-weather"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justincampbell/emoji-weather/releases/download/v0.3.0/emoji-weather_0.3.0_linux_amd64.tar.gz"
      sha256 "0f67bd65933c22b76fc4849e6143b6c21fdc7a52cb7123b8ef9dc3ffe7d457d9"
      define_method(:install) do
        bin.install "emoji-weather"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justincampbell/emoji-weather/releases/download/v0.3.0/emoji-weather_0.3.0_linux_arm64.tar.gz"
      sha256 "b2b6db082a6836a6b015f46c9878db932927d8fd8350449accaffc9f63ad8067"
      define_method(:install) do
        bin.install "emoji-weather"
      end
    end
  end
end
