# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revise < Formula
  desc "A terminal UI for reviewing local git changes and sending feedback to Claude Code"
  homepage "https://github.com/justincampbell/revise"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justincampbell/revise/releases/download/v0.1.5/revise_0.1.5_darwin_amd64.tar.gz"
      sha256 "a57655aeb6aa1939a5af5052622eed7b03f58fa56d4503dc70ce17e7cbc2eb6d"

      define_method(:install) do
        bin.install "revise"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justincampbell/revise/releases/download/v0.1.5/revise_0.1.5_darwin_arm64.tar.gz"
      sha256 "f6a1384f5b8cd2d1f841e4725f8e19a8a70a22f2459b3594fea72d64e2f4f7b2"

      define_method(:install) do
        bin.install "revise"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justincampbell/revise/releases/download/v0.1.5/revise_0.1.5_linux_amd64.tar.gz"
      sha256 "f95a92fa2853edd69f572beaf39243ad11ae0b6d1340ac951e965ba3378960a3"
      define_method(:install) do
        bin.install "revise"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justincampbell/revise/releases/download/v0.1.5/revise_0.1.5_linux_arm64.tar.gz"
      sha256 "d194340794bfe375570c3290d87b5c986d6fdae0849b98e3edb06b1a64a0f20a"
      define_method(:install) do
        bin.install "revise"
      end
    end
  end
end
