# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revise < Formula
  desc "A terminal UI for reviewing local git changes and sending feedback to Claude Code"
  homepage "https://github.com/justincampbell/revise"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justincampbell/revise/releases/download/v0.1.3/revise_0.1.3_darwin_amd64.tar.gz"
      sha256 "01016d4c74d84ad40c0ef980537b5938134fb0d34c51b24da450cf2c76107d5a"

      define_method(:install) do
        bin.install "revise"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justincampbell/revise/releases/download/v0.1.3/revise_0.1.3_darwin_arm64.tar.gz"
      sha256 "283ece4502d992fa89eb34b64655fee15d772c60d4cb4442ba83dd48a41feddc"

      define_method(:install) do
        bin.install "revise"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justincampbell/revise/releases/download/v0.1.3/revise_0.1.3_linux_amd64.tar.gz"
      sha256 "81ae1026f86e8a5d99a3934f42e4035c37b392e9059e57cd91a8a1c60beb6b7c"
      define_method(:install) do
        bin.install "revise"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justincampbell/revise/releases/download/v0.1.3/revise_0.1.3_linux_arm64.tar.gz"
      sha256 "12d0397779c52ba64be8b86d1e267a1dd00494b9e8f3b74100fec36dbe07e613"
      define_method(:install) do
        bin.install "revise"
      end
    end
  end
end
