# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rmt8l < Formula
  desc "CLI for backing up and inspecting Radiomaster T8L radio configuration over USB"
  homepage "https://github.com/justincampbell/rmt8l"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/justincampbell/rmt8l/releases/download/v0.1.0/rmt8l_0.1.0_darwin_amd64.tar.gz"
    sha256 "037487ce584da0f4047b9e99e7ccebada9d216b3c210c900da2f5c68c4763ba3"

    define_method(:install) do
      bin.install "rmt8l"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/justincampbell/rmt8l/releases/download/v0.1.0/rmt8l_0.1.0_darwin_arm64.tar.gz"
    sha256 "45e99fd200717128093cb57a50923701f72945eec20dda319a8686944c9a238e"

    define_method(:install) do
      bin.install "rmt8l"
    end
  end
end
