# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShortcutStatusline < Formula
  desc "A CLI that prints info about the current Shortcut story for use in a shell statusline"
  homepage "https://github.com/justincampbell/shortcut-statusline"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justincampbell/shortcut-statusline/releases/download/v0.2.0/shortcut-statusline_0.2.0_darwin_amd64.tar.gz"
      sha256 "4e12c52ccb6da2dae3ed42d80e626f665d9504c8a25ca9e43a171901e03df1d6"

      define_method(:install) do
        bin.install "shortcut-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justincampbell/shortcut-statusline/releases/download/v0.2.0/shortcut-statusline_0.2.0_darwin_arm64.tar.gz"
      sha256 "458a3abc741970320476b24a161d583def3fdb142d1252636759ceec1658865c"

      define_method(:install) do
        bin.install "shortcut-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justincampbell/shortcut-statusline/releases/download/v0.2.0/shortcut-statusline_0.2.0_linux_amd64.tar.gz"
      sha256 "6866cc7624f2c510eac1a47388775b7b72e677fe36108a6bd87eaed1969b55a1"
      define_method(:install) do
        bin.install "shortcut-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justincampbell/shortcut-statusline/releases/download/v0.2.0/shortcut-statusline_0.2.0_linux_arm64.tar.gz"
      sha256 "7581070201b53d213aff47730f857642fea74afa6579e5df7b31ff40e090d937"
      define_method(:install) do
        bin.install "shortcut-statusline"
      end
    end
  end
end
